

#region function Build-MyFCGScriptGenEMail
function Build-MyFCGScriptGenEMail ()
{
  <#
    .SYNOPSIS
      Function to do something specific
    .DESCRIPTION
      Function to do something specific
    .PARAMETER Value
      Value Command Line Parameter
    .EXAMPLE
      Build-MyFCGScriptGenEMail -Value "String"
    .NOTES
      Original Function By
  #>
  [CmdletBinding()]
  param (
    [parameter(Mandatory = $True)]
    [String]$ScriptName
  )
  Write-Verbose -Message "Enter Function Build-MyFCGScriptGenEMail"

  $StringBuilder = [System.Text.StringBuilder]::New()

  #region ******** My Code ********
  [Void]$StringBuilder.AppendLine("#region ******** Generate E-Mail Class ********")
  [Void]$StringBuilder.AppendLine("")

  #region ******** Generate E-Mail Class ********
  [Void]$StringBuilder.AppendLine("#region class GenMyEMail - Generate HTML E-mail Messages with Custom Colors and Styles")
  [Void]$StringBuilder.AppendLine("class GenMyEMail")
  [Void]$StringBuilder.AppendLine("{")
  [Void]$StringBuilder.AppendLine("  # Default Message Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$BodyColor = `"White`"")
  [Void]$StringBuilder.AppendLine("  [String]`$TextColor = `"Black`"")
  [Void]$StringBuilder.AppendLine("  [String]`$HeaderColor = `"#1A2C42`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Default List Color")
  [Void]$StringBuilder.AppendLine("  [String]`$ListColor = `"Black`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Default Property/Value Table Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$PropertyColor = `"PaleGreen`"")
  [Void]$StringBuilder.AppendLine("  [String]`$ValueColor = `"White`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Default Info/Data Table Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$TitleInfo = `"LightSkyBlue`"")
  [Void]$StringBuilder.AppendLine("  [String]`$ColumnInfo = `"LightBlue`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Success Table Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$TitleSuccess = `"mediumspringgreen`"")
  [Void]$StringBuilder.AppendLine("  [String]`$ColumnSuccess = `"PaleGreen`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Warning Table Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$TitleWarning = `"Gold`"")
  [Void]$StringBuilder.AppendLine("  [String]`$ColumnWarning = `"khaki`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Error Table Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$TitleError = `"LightCoral`"")
  [Void]$StringBuilder.AppendLine("  [String]`$ColumnError = `"LightPink`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Status Colors")
  [Void]$StringBuilder.AppendLine("  [String]`$StatusInfo = `"Navy`"")
  [Void]$StringBuilder.AppendLine("  [String]`$StatusSuccess = `"ForestGreen`"")
  [Void]$StringBuilder.AppendLine("  [String]`$StatusWarning = `"Peru`"")
  [Void]$StringBuilder.AppendLine("  [String]`$StatusError = `"FireBrick`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Alternate Row Colors")
  [Void]$StringBuilder.AppendLine("  [String[]]`$RowColor = @(`"White`", `"Gainsboro`")")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Generated Message Content")
  [Void]$StringBuilder.AppendLine("  [System.Text.StringBuilder]`$SB = [System.Text.StringBuilder]::new()")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Initialize E-mail with Default Colors")
  [Void]$StringBuilder.AppendLine("  GenMyEMail ([String]`$HeaderText, [String]`$CompanyLogo, [Int]`$Width, [Int]`$Height)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.InitilizeEMail(`$This.BodyColor, `$This.TextColor, `$This.HeaderColor, `$HeaderText, `$CompanyLogo, `$Width, `$Height)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Initialize E-mail with Custom Colors")
  [Void]$StringBuilder.AppendLine("  GenMyEMail ([String]`$BodyColor, [String]`$TextColor, [String]`$HeaderColor, [String]`$HeaderText, [String]`$CompanyLogo, [Int]`$Width, [Int]`$Height)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.InitilizeEMail(`$BodyColor, `$TextColor, `$HeaderColor, `$HeaderText, `$CompanyLogo, `$Width, `$Height)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Hidden method to generate the initial HTML for the e-mail message")
  [Void]$StringBuilder.AppendLine("  hidden [Void] InitilizeEMail ([String]`$BodyColor, [String]`$TextColor, [String]`$HeaderColor, [String]`$HeaderText, [String]`$CompanyLogo, [Int]`$Width, [Int]`$Height)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<style>body {font-family: Calibri, Arial, sans-serif; font-size: 16px; color: `$(`$TextColor); background-color: `$(`$BodyColor); margin: 0; padding: 20px;} ``")
  [Void]$StringBuilder.AppendLine("                            .email-header {color: `$(`$HeaderColor); font-size: 24px; font-weight: bold; margin: 0;} ``")
  [Void]$StringBuilder.AppendLine("                            .email-body p {margin: 0px 0px 12px 0px; line-height: 1.6;} ``")
  [Void]$StringBuilder.AppendLine("                            .email-signature {margin-top: 32px; padding-top: 16px; font-size: 16px; color: `$(`$HeaderColor); line-height: 1.7;} ``")
  [Void]$StringBuilder.AppendLine("                            .email-signature .sig-message {color: `$(`$TextColor);} ``")
  [Void]$StringBuilder.AppendLine("                     </style><body><div><img alt='Company Logo' width='`$(`$Width)' height='`$(`$Height)' src='data:image/jpeg;base64, `$(`$CompanyLogo)' /><div><p class='email-header'>`$(`$HeaderText)</p></div></div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add text to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddText ([String]`$Message)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<p>`$(`$Message)</p>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a mailto link to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddMailTo ([String]`$Message, [String]`$LinkText, [String]`$To, [String]`$CC, [String]`$Subject, [String]`$Body)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<p>`$(`$Message) <a href='mailto:`$(`$To)?cc=`$(`$CC)&subject=`$(`$Subject)&body=`$(`$Body)'>`$(`$LinkText)</a></p>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a hyperlink to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddLink ([String]`$Message, [String]`$LinkText, [String]`$URL)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<p>`$(`$Message) <a href='`$(`$URL)'>`$(`$LinkText)</a></p>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add HTML to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddAnyHTML ([String]`$HTML)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`$HTML) | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to Set Default List Style")
  [Void]$StringBuilder.AppendLine("  [Void] SetListStyle ()")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SetListStyle(`$This.ListColor)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to Set Custom List Style")
  [Void]$StringBuilder.AppendLine("  [Void] SetListStyle ([String]`$ItemColor)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<style>ul, ol {color: `$(`$ItemColor);} ul li, ol li {color: `$(`$ItemColor);} ul li::marker, ol li::marker {color: `$(`$ItemColor);}</style>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a ul list to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddList ([String[]]`$ListItems)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendList(`$ListItems, `$False)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a ul/ol list to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddList ([String[]]`$ListItems, [Bool]`$Ordered)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = (`$ListItems | ForEach-Object -Process { `"<li>`$(`$PSItem)</li>`" }) -join ''")
  [Void]$StringBuilder.AppendLine("    if (`$Ordered)")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append(`"<div class='data-table-wrapper'><ol>`$(`$TmpString)</ol></div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("    else")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append(`"<div class='data-table-wrapper'><ul>`$(`$TmpString)</ul></div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a ul list to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddList ([HashTable]`$ListItems)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendList(`$ListItems, `$False)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a ul/ol list to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddList ([HashTable]`$ListItems, [Bool]`$Ordered)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = (`$ListItems.GetEnumerator() | ForEach-Object -Process { `"<li><b>`$(`$PSItem.Key): </b>`$(`$PSItem.Value)</li>`" }) -join ''")
  [Void]$StringBuilder.AppendLine("    if (`$Ordered)")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append(`"<div class='data-table-wrapper'><ol>`$(`$TmpString)</ol></div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("    else")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append(`"<div class='data-table-wrapper'><ul>`$(`$TmpString)</ul></div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to Set Default Table Style")
  [Void]$StringBuilder.AppendLine("  [Void] SetTableStyle ()")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SetTableStyle(`$This.TitleColor, `$This.ColumnColor, `$This.TextColor, `$This.BorderColor)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to Set Custom Table Style")
  [Void]$StringBuilder.AppendLine("  [Void] SetTableStyle ([String]`$TitleColor, [String]`$ColumnColor, [String]`$TextColor, [String]`$BorderColor)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<style>.data-table-wrapper {margin: 16px 0; overflow-x: auto;} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table {border-collapse: collapse; font-size: 14px; color: `$(`$TextColor);} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .table-title, .data-table .col-header {font-size: 16px; text-align: center; font-weight: bold;} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .table-title {color: `$(`$TitleColor);} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .col-header {color: `$(`$ColumnColor);} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .table-title, .data-table .col-header, .data-table .col-right, .data-table .col-left, .data-table .cell-left, .data-table .cell-center, .data-table .cell-right {padding: 2px 8px; white-space: nowrap; border: 1px solid `$(`$BorderColor);} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .col-right {text-align: right; font-weight: bold;} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .col-left, .data-table .cell-left {text-align: left;} ``")
  [Void]$StringBuilder.AppendLine("                            .data-table .cell-center {text-align: center;} ``")
  [Void]$StringBuilder.AppendLine("                    </style>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table title row to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableTitle ([Int]`$ColumnCount, [String]`$TitleText, [Bool]`$EndTitle)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendTableTitle(`$This.TitleInfo, `$ColumnCount, `$TitleText, `$EndTitle)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table title row to the e-mail message body with a custom background color")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableTitle ([String]`$BackgroundColor, [Int]`$ColumnCount, [String]`$TitleText, [Bool]`$EndTitle)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = `"<div class='data-table-wrapper'><table class='data-table'><thead><tr style='background-color:{0}; '><th class='table-title' colspan='{1}'>{2}</th></tr>{3}`"")
  [Void]$StringBuilder.AppendLine("    if (`$EndTitle)")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append([String]::Format(`$TmpString, `$BackgroundColor, `$ColumnCount, `$TitleText, `"</thead><tbody>`")) | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("    else")
  [Void]$StringBuilder.AppendLine("    {")
  [Void]$StringBuilder.AppendLine("      `$This.SB.Append([String]::Format(`$TmpString, `$BackgroundColor, `$ColumnCount, `$TitleText, `"`")) | Out-Null")
  [Void]$StringBuilder.AppendLine("    }")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table column header row to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableColumns ([String[]]`$ColumnNames)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendTableColumns(`$This.ColumnInfo, `$ColumnNames)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table column header row to the e-mail message body with a custom background color")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableColumns ([String]`$BackgroundColor, [String[]]`$ColumnNames)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = `"<tr style='background-color:`$(`$BackgroundColor); '>`$((@(1..`$(`$ColumnNames.Count)) | ForEach-Object -Process { `"<th class='col-header'>{`$(`$PSItem - 1)}</th>`" }) -join '')</tr></thead><tbody>`"")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append([String]::Format(`$TmpString, [Object[]]`$ColumnNames)) | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table row with a status column to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableRow ([String]`$StatusColor, [String]`$StatusText, [String[]]`$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendTableRow(`$This.BodyColor, `$StatusColor, `$StatusText, `$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table row with a status column to the e-mail message body with a custom background color")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableRow ([String]`$BackgroundColor, [String]`$StatusColor, [String]`$StatusText, [String[]]`$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = `"<tr style='background-color:`$(`$BackgroundColor)'><td class='cell-center' style='color:`$(`$StatusColor);  font-weight:bold; '>`$(`$StatusText)</td>`$((@(1..`$(`$ColumnValues.Count)) | ForEach-Object -Process { `"<td class='cell-left'>{`$(`$PSItem - 1)}</td>`" }) -join '')</tr>`"")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append([String]::Format(`$TmpString, [Object[]]`$ColumnValues)) | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table row to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableRow ([String[]]`$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendTableRow(`$This.BodyColor, `$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a table row to the e-mail message body with a custom background color")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableRow ([String]`$BackgroundColor, [String[]]`$ColumnValues)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$TmpString = `"<tr style='background-color:`$(`$BackgroundColor)'>`$((@(1..`$(`$ColumnValues.Count)) | ForEach-Object -Process { `"<td class='cell-left'>{`$(`$PSItem - 1)}</td>`" }) -join '')</tr>`"")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append([String]::Format(`$TmpString, [Object[]]`$ColumnValues)) | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a property/value pair row to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableProperty ([String]`$PropertyName, [String]`$PropertyValue)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.AppendTableProperty(`$This.PropertyColor, `$PropertyName, `$This.ValueColor, `$PropertyValue)")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a property/value pair row to the e-mail message body with custom background colors")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableProperty ([String]`$PropertyBackgroundColor, [String]`$PropertyName, [String]`$ValueBackgroundColor, [String]`$PropertyValue)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<tr><td class='col-right' style='background-color:`$(`$PropertyBackgroundColor); '>`$(`$PropertyName):</td><td class='col-left' style='background-color:`$(`$ValueBackgroundColor); '>`$(`$PropertyValue)</td></tr>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to end the table and add spacing after the table in the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddTableEnd ()")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"</tbody></table>&nbsp;</div>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a signature block to the e-mail message body")
  [Void]$StringBuilder.AppendLine("  [Void] AddSignature ([String]`$Signature, [String]`$Message)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<div class='email-signature'><div class='sig-name' style='font-weight: bold;'>`$(`$Signature)</div><div class='sig-message'>`$(`$Message)</div></div><br><br></body>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to add a signature block to the e-mail message body with an optional URL")
  [Void]$StringBuilder.AppendLine("  [Void] AddSignature ([String]`$Signature, [String]`$Message, [String]`$URLText, [String]`$URLLink)")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    `$This.SB.Append(`"<div class='email-signature'><hr><div class='sig-name' style='font-weight: bold;'>`$(`$Signature)</div><div class='sig-message'>`$(`$Message)</div><div><a href='`$(`$URLLink)' target='_blank'>`$(`$URLText)</a></div></div><br><br></body>`") | Out-Null")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("  # Method to retrieve the generated e-mail message body as a string")
  [Void]$StringBuilder.AppendLine("  [String] GetEMailBody ()")
  [Void]$StringBuilder.AppendLine("  {")
  [Void]$StringBuilder.AppendLine("    return `$This.SB.ToString()")
  [Void]$StringBuilder.AppendLine("  }")
  [Void]$StringBuilder.AppendLine("}")
  [Void]$StringBuilder.AppendLine("#endregion class GenMyEMail - Generate HTML E-mail Messages with Custom Colors and Styles")
  [Void]$StringBuilder.AppendLine("")  
  #endregion ******** Generate E-Mail Class ********

  #region ******** Generate E-Mail Sample Code ********
  [Void]$StringBuilder.AppendLine("#region Generate / Send Sample E-Mail")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("<#")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Create an instance of the GenMyEMail class and generate the e-mail content")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail = [GenMyEMail]::new(`"This is My Example E-Mail Header Message`", `$Base64Logo, 200, 38)")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Add Message Text")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddText(`"Dear Sir or Madam,`")")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddText(`"This is a test e-mail generated by PowerShell.<br>Below you can find some example tables with different styles and content.`")")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddMailTo(`"To Respond to this e-mail`", `"Click here`", (`$MailParams.From), (`$MailParams.To), `"Sample E-Mail Subject`", `"Greetings,%0A%0AThis is a sample e-mail body generated by PowerShell.%0A`")")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddLink(`"For more information`", `"Click here`", `"https://some.website.net/`")")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Add List")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.SetListStyle()")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddList(@(`"Item 1`", `"Item 2`", `"Item 3`", `"Item 4`"), `$False)")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Add Property/Value Tables")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.SetTableStyle()")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableTitle(2, `"Property Table Title`", `$True)")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableProperty(`"Property 1`", `"Value 1`")")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableProperty(`"Property 2`", `"Value 2`")")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableEnd()")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Add Info/Data Table")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableTitle(5, `"Info Test Table Title`", `$False)")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableColumns(@(`"Status`", `"Column 1`", `"Column 2`", `"Column 3`", `"Column 4`"))")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableRow((`$GenMyEMail.RowColor[0]), `$GenMyEMail.StatusInfo, `"Information`", @(`"Value 1`", `"Value 2`", `"Value 3`", `"Value 4`"))")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableRow((`$GenMyEMail.RowColor[1]), `$GenMyEMail.StatusSuccess, `"Success`", @(`"Value 1`", `"Value 2`", `"Value 3`", `"Value 4`"))")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableRow((`$GenMyEMail.RowColor[0]), `$GenMyEMail.StatusWarning, `"Warning`", @(`"Value 1`", `"Value 2`", `"Value 3`", `"Value 4`"))")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableRow((`$GenMyEMail.RowColor[1]), `$GenMyEMail.StatusError, `"Error`", @(`"Value 1`", `"Value 2`", `"Value 3`", `"Value 4`"))")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddTableEnd()")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Add Signature")
  [Void]$StringBuilder.AppendLine("`$GenMyEMail.AddSignature(`"Best regards,`", `"This was a example e-mail generated by PowerShell.`", `"Some Web Site`", `"https://some.website.net/`")")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Send E-Mail Parameters")
  [Void]$StringBuilder.AppendLine("`$MailParams = @{")
  [Void]$StringBuilder.AppendLine("  `"SmtpServer`"    = `"smtphost.fakedomain.qaz`"")
  [Void]$StringBuilder.AppendLine("  `"Port`"          = 25")
  [Void]$StringBuilder.AppendLine("  `"From`"          = `"gomer.pyle@fakedomain.qaz`"")
  [Void]$StringBuilder.AppendLine("  `"to`"            = `"gomer.pyle@fakedomain.qaz`"")
  [Void]$StringBuilder.AppendLine("  `"BodyAsHtml`"    = `$True")
  [Void]$StringBuilder.AppendLine("  `"WarningAction`" = `"SilentlyContinue`"")
  [Void]$StringBuilder.AppendLine("}")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("# Send the e-mail using Send-MailMessage")
  [Void]$StringBuilder.AppendLine("Send-MailMessage @MailParams -Body (`$GenMyEMail.GetEMailBody()) -Subject `"PowerShell Generated Example E-Mail`"")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("#>")
  [Void]$StringBuilder.AppendLine("")
  [Void]$StringBuilder.AppendLine("#endregion Generate / Send Sample E-Mail")
  [Void]$StringBuilder.AppendLine("")
  #endregion ******** Generate E-Mail Sample Code ********

  [Void]$StringBuilder.AppendLine("#endregion ******** Generate E-Mail Class ********")
  [Void]$StringBuilder.AppendLine("")
  #endregion ******** My Code ********

  $StringBuilder.ToString()
  $StringBuilder = $Null

  [System.GC]::Collect()
  [System.GC]::WaitForPendingFinalizers()

  Write-Verbose -Message "Exit Function Build-MyFCGScriptGenEMail"
}
#endregion function Build-MyFCGScriptGenEMail
